import requests
import dash
from dash import dcc, html
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

def fetch_random_user():
    url = "https://randomuser.me/api/"
    response = requests.get(url)
    data = response.json()
    return data['results'][0]

random_user = fetch_random_user()

app.layout = html.Div([
    html.H1("Random User"),
    html.H1("Seshagiri Somepalli Dashboard"),
    html.H1("PDS_Assignment"),
    html.H3("Data is randomly generated by using free API"),
    html.Button("Fetch Random User", id="fetch-btn", n_clicks=0),
    html.Div(id="user-output")
])

@app.callback(
    Output("user-output", "children"),
    [Input("fetch-btn", "n_clicks")]
)
def update_user_info(n_clicks):
    if n_clicks > 0:
        random_user = fetch_random_user()
        user_info = html.Div([
            html.H3("Random User Data:"),
            html.P(f"Name: {random_user['name']['first']} {random_user['name']['last']}"),
            html.P(f"Gender: {random_user['gender']}"),
            html.P(f"Email: {random_user['email']}"),
            html.P(f"Location: {random_user['location']['city']}, {random_user['location']['state']}, {random_user['location']['country']}")
        ])
        return user_info

if __name__ == "__main__":
    app.run_server(debug=True)
